# Generated by Django 3.2.5 on 2022-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_real_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='bcrm_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rt_ud',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketing_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
