# Generated by Django 3.2.5 on 2022-03-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0002_auto_20220326_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='rt_ud',
            new_name='rt_id',
        ),
    ]
