# Generated by Django 3.2.5 on 2022-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0004_auto_20220326_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tarif_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
