# Generated by Django 3.2.5 on 2022-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0005_alter_ticket_tarif_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'managed': True, 'ordering': ['car_name']},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'managed': True, 'ordering': ['channel_name']},
        ),
        migrations.AlterModelOptions(
            name='coloradjustment',
            options={'managed': True, 'ordering': ['color_adjustment_name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'managed': True, 'ordering': ['district']},
        ),
        migrations.AlterModelOptions(
            name='gpontype',
            options={'managed': True, 'ordering': ['gpon_type']},
        ),
        migrations.AlterModelOptions(
            name='lancable',
            options={'managed': True, 'ordering': ['lan_cable_name']},
        ),
        migrations.AlterModelOptions(
            name='muft',
            options={'managed': True, 'ordering': ['muft_name']},
        ),
        migrations.AlterModelOptions(
            name='opticalcable',
            options={'managed': True, 'ordering': ['optical_cable_name']},
        ),
        migrations.AlterModelOptions(
            name='otherdevice',
            options={'managed': True, 'ordering': ['other_device_name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True, 'ordering': ['region']},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'managed': True, 'ordering': ['service_type']},
        ),
        migrations.AlterModelOptions(
            name='spliter',
            options={'managed': True, 'ordering': ['spliter_name']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': True, 'ordering': ['fullname'], 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='stbtype',
            options={'managed': True, 'ordering': ['stb_name']},
        ),
        migrations.AlterModelOptions(
            name='ticketthread',
            options={'managed': True, 'ordering': ['ticket_thread']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'managed': True, 'ordering': ['warehouse']},
        ),
        migrations.AlterModelOptions(
            name='wifirouter',
            options={'managed': True, 'ordering': ['wifi_router_name']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='comments',
            new_name='tech_comment',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bcrm_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch_type',
            field=models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('B2C PS', 'B2C PS'), ('Other', 'Other')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rt_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Measuring', 'Measuring'), ('Servicing', 'Servicing'), ('Constraction', 'Constraction'), ('Welding', 'Welding'), ('Design', 'Design'), ('Connection', 'Connection')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketing_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
