# Generated by Django 3.2.5 on 2022-03-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0010_auto_20220331_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stb_2_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stb_2_type',
            field=models.ForeignKey(blank=True, db_column='stb_2_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stb_2', to='fond_main.stbtype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stb_3_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stb_3_type',
            field=models.ForeignKey(blank=True, db_column='stb_3_type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stb_3', to='fond_main.stbtype'),
        ),
    ]
