# Generated by Django 3.2.5 on 2022-03-31 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0011_auto_20220331_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='muft_2',
            field=models.ForeignKey(blank=True, db_column='ticket_muft_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_muft_2', to='fond_main.muft'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='muft_3',
            field=models.ForeignKey(blank=True, db_column='ticket_muft_3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_muft_3', to='fond_main.muft'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spliter_2',
            field=models.ForeignKey(blank=True, db_column='spliter_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_spliter_2', to='fond_main.spliter'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spliter_3',
            field=models.ForeignKey(blank=True, db_column='spliter_3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_spliter_3', to='fond_main.spliter'),
        ),
    ]
