# Generated by Django 3.2.5 on 2022-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0012_auto_20220331_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='muft_2_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='muft_3_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='muft_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spliter_2_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spliter_3_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spliter_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
