# Generated by Django 3.2.5 on 2022-03-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0013_auto_20220331_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='lan_cable_begin',
            new_name='ftp_cable_begin',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='lan_cable_code',
            new_name='ftp_cable_code',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='lan_cable_end',
            new_name='ftp_cable_end',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='lan_cable_length',
            new_name='ftp_cable_length',
        ),
    ]
