# Generated by Django 3.2.5 on 2022-03-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0014_auto_20220331_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='utp_cable_begin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='utp_cable_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='utp_cable_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='utp_cable_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
