# Generated by Django 3.2.5 on 2022-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0015_auto_20220331_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Config', 'Config'), ('Done', 'Done'), ('Reject', 'Reject')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Measuring', 'Measuring'), ('Servicing', 'Servicing'), ('Construction', 'Construction'), ('Welding', 'Welding'), ('Design', 'Design'), ('Connection', 'Connection')], default='', max_length=60),
        ),
    ]
