# Generated by Django 3.2.5 on 2022-04-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0018_alter_ticketmistake_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmistake',
            options={'managed': True, 'ordering': ['ticket_mistake_name'], 'verbose_name_plural': 'Ticket Mistake'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='mistake_author',
            field=models.ForeignKey(blank=True, db_column='mistake_author', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_mistake_author', to='fond_main.authuser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qualiter',
            field=models.ForeignKey(blank=True, db_column='qualiter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_qualiter', to='fond_main.authuser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quality_comment',
            field=models.CharField(blank=True, default='', max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quality_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quality_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quality_mistake',
            field=models.ForeignKey(blank=True, db_column='quality_mistake', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_quality_mistake', to='fond_main.ticketmistake'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quality_status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Incomplete', 'Incomplete'), ('Corrected', 'Corrected'), ('Solved', 'Solved'), ('Punishment', 'Punishment')], default='', max_length=60),
        ),
    ]
