# Generated by Django 3.2.5 on 2022-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0021_alter_ticket_quality_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mistake_part',
            field=models.CharField(blank=True, choices=[('Operational Part', 'Operational Part'), ('Config Part', 'Config Part'), ('Operational/Config Part', 'Operational/Config Part')], default='', max_length=60, null=True),
        ),
    ]
