# Generated by Django 3.2.5 on 2022-05-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0022_ticket_mistake_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='difficaulty',
            field=models.FloatField(blank=True, choices=[('Normal', 1), ('Hard', 1.25), ('Wery Hard', 1.5)], default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='distance',
            field=models.CharField(blank=True, choices=[('', ''), ('<30', '<30'), ('30-80', '30-80'), ('80-150', '80-150'), ('>150', '>150')], default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tower',
            field=models.ForeignKey(blank=True, db_column='tower', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tower', to='fond_main.car'),
        ),
    ]
