# Generated by Django 3.2.5 on 2022-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0024_auto_20220601_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extra_work',
            field=models.CharField(blank=True, choices=[('', ''), ('Overtime', 'Overtime'), ('Weekend', 'Weekend')], default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(blank=True, choices=[('', ''), ('Region', 'Region')], default='', max_length=60, null=True),
        ),
    ]
