# Generated by Django 3.2.5 on 2022-06-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond_main', '0025_auto_20220601_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='worktime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
